"""add user instructions

Revision ID: fedea133711f
Revises: f4a17c9be620
Create Date: 2026-09-24 15:04:24.501848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fedea133711f"
down_revision: str | Sequence[str] | None = "f4a17c9be620"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("instructions", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "instructions")
    # ### end Alembic commands ###
