"""add attachment key unique

Revision ID: 255c9aac4725
Revises: fedea133711f
Create Date: 2026-09-28 10:03:03.829193

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "255c9aac4725"
down_revision: str | Sequence[str] | None = "fedea133711f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("attachment_key_key"), "attachment", ["key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("attachment_key_key"), "attachment", type_="unique")
    # ### end Alembic commands ###
